version: '2'
services:
  guessmycategory-app:
    image: guessmycategory
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://guessmycategory-mariadb:3306/guessmycategory
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
    ports:
      - 8080:8080
  guessmycategory-mariadb:
    extends:
      file: mariadb.yml
      service: guessmycategory-mariadb
